### PR TITLE
Capstone Project complete

### PR DESCRIPTION
**Pull request by ger619**
- Here is a link to my loom video [loom link](https://www.loom.com/share/9fb83c5829d246b7bc4aab382e586d47)

- You should personalize the content of your page. Choose a topic that is different than the one in the original design.

- You should follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including:
  - Colors.
  - Typography: font face, size and weight.
  - Layout: composition and space between elements.
  - The pages should look almost identical to the original design. Small adjustments like text or image changes are acceptable.
  - You can use a CSS framework (for example Bootstrap) for styling if you want to.

- You should build only these 2 pages:
  - The home page.
  - The about page.
- Each of these pages should have versions for 2 different screen sizes:

- Mobile: up to 768px wide.
- Desktop: 768px or wider.
- Interactions

- Links

- The home page should have a link in the menu to the about page.

- The logo in the header links to the home page.

- Mobile menu

- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.

- There are no guidelines for the mobile menu in the docs, but you should implement it so it is consistent with the design (colours, typography, spacings, etc.).

- The mobile menu should have a close (X) button that closes the menu.

- Dynamic page

- The section "Featured speakers" should be created dynamically in JavaScript.

- You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.

### CODE REVIEW

**Review by CollinsTatang — CHANGES_REQUESTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no deployment live link.
All group member has to make multiple commits to the project code base.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ger619** [comment]
Hello @CollinsTatang This is a capstone project. I work on it alone and submit it alone. A deployment link can only run on main and i cant push to main unless I merge with the main branch once my code is approved.

**Comment by CollinsTatang** [comment]
> 

Hi @ger619 

- [ ] Great job so far, you should make multiple commits to your codebase next time.
- [ ] Kindly deployed your project with the feature branch you are working on and when is approved you can now merge to the main branch.

**Comment by ger619** [comment]
Hello @CollinsTatang the pull request is on a  feature branch called capstone-con, and i have made multiple commits if you look at it closely. Does the number of commits really matter?

**Comment by CollinsTatang** [comment]
> Hello @CollinsTatang the pull request is on a feature branch called capstone-con, and i have made multiple commits if you look at it closely. Does the number of commits really matter?

Yeah, multiple commits make your project look more professional and give you a clear understanding of the different features committed to the app for easy maintenance in the future. I see just one commit in your PR

**Review by Kingstalux — COMMENTED** [review]
Hi @ger619, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Kindly provide the correct pull request description 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Pull request closed without merging**
